version: '3.1'

services:

  db:
    image: postgres:14-alpine
    container_name: postgres14
    restart: always
    volumes:
      - ./DockerVolumes/postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: surelink-db
    ports:
      - "5432:5432"

